/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Quote = IDL.Record({ 'text' : IDL.Text, 'author' : IDL.Text });

export const idlService = IDL.Service({
  'getDailyQuote' : IDL.Func([], [Quote], []),
  'getRandomQuote' : IDL.Func([], [Quote], []),
  'getReverseLifeClockStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'daysElapsed' : IDL.Nat,
          'totalDays' : IDL.Nat,
          'percentUsed' : IDL.Nat,
          'daysRemaining' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Quote = IDL.Record({ 'text' : IDL.Text, 'author' : IDL.Text });
  
  return IDL.Service({
    'getDailyQuote' : IDL.Func([], [Quote], []),
    'getRandomQuote' : IDL.Func([], [Quote], []),
    'getReverseLifeClockStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'daysElapsed' : IDL.Nat,
            'totalDays' : IDL.Nat,
            'percentUsed' : IDL.Nat,
            'daysRemaining' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };